### PR TITLE
first shot at including modifiers

### PR DESCRIPTION
**Pull request by kraftner**
see https://github.com/SC5/sc5-styleguide/issues/784

### CODE REVIEW

**Comment by kraftner** [comment]
Okay this was a first shot and apparently still has some issues. Sorry for the mess, I'll try to clean it up on monday.

**Comment by kraftner** [comment]
Sorry for the mess. I'll create an new clean PR once this is ready to go in.

But first I'd need some feedback if this is working for you.
Also I'd like to add this to the test coverage but not really sure were to start.

**Comment by Grienauer** [comment]
+1

**Comment by varya** [comment]
Looks good. I would also add the tests about this case in here https://github.com/SC5/sc5-styleguide/blob/master/test/unit/modules/section-references.test.js

**Comment by kraftner** [comment]
So, this is the first time I've written a JS test, hopefully it is useful :smile: 

If this all looks good to you I can create a new, clean PR if you don't want to merge all this separate commits.

**Comment by varya** [comment]
Yes, sure. I'll merge the new one.

**Comment by kraftner** [comment]
Okay this finally made me get into the magic realm of rebasing and force-pushing.

I think this is now ready to be merged.

**Comment by varya** [comment]
Thank you very much!

**Comment by kraftner** [comment]
Thank **you** for everything else!

You can also close #784 now.

**Pull request merged**
