### PR TITLE
Issue 499: Allowed for variable chaining (to dev)

### PR DESCRIPTION
**Pull request by paul-barry-kenzan**
Changing the destination branch of [PR#692](https://github.com/SC5/sc5-styleguide/pull/692)

### CODE REVIEW

**Comment by hannu** [comment]
Commit log looks bit weird. Could you rebase this against dev branch so we could get cleaner changeset?

**Comment by paul-barry-kenzan** [comment]
@hannu, Yes, I'll get that submitted today.

**Comment by paul-barry-kenzan** [comment]
@hannu, Just rebased and commited.

**Comment by varya** [comment]
I took your branch and rebased it against dev, so that the PR now has only your 2 commits.
Unfortunately I can only create a new OR on behalf of me. But inside there are your commits, it is visible that you are the author. https://github.com/SC5/sc5-styleguide/pull/707

**Comment by paul-barry-kenzan** [comment]
@varya Thanks and sorry about the commit mess.

**Pull request closed without merging**
