### PR TITLE
Make the catch log the right error in case of syntax parsing error

### PR DESCRIPTION
**Pull request by Qt-dev**
I caught a problem where my syntax was causing an error in the code generation.
The problem was with less, with a line that looked like: 

```less
width: calc(~"100%" - @myvar); 
```

The only log I was getting was "undefined" since it was logging ```error.stack``` but that error does not have a stack.

This change shows the full error so that user get more info on what went wrong when it happens there.

There is a problem with less processing too somehow but we need to identify it properly to create an issue for it

### CODE REVIEW

**Comment by Qt-dev** [comment]
I am not sure why coveralls doesn't pass when 100% of the tests are passing and it tells me it got a -0.0% decrease

**Comment by shooksm** [comment]
Travis is grousing about installing PhantomJS. If I had a dollar for every time PhantomJS stopped an npm install I would not need to develop anymore. You might just try rerunning the build. Simply close and reopen the pull request to get Travis to restart.

**Comment by varya** [comment]
Hi. Could you rebase with master please? I'll merge it right away after that.

**Comment by Qt-dev** [comment]
I took my time but https://github.com/SC5/sc5-styleguide/blob/master/lib/styleguide.js#L413 seems to do the trick anyway. This can be closed :)

**Pull request closed without merging**
